name: Todo CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  # 1) Build do app
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache de dependências Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

  # 2) Unit tests
  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache de dependências Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Run unit tests
        run: ./gradlew unitTests

  # 3) Integration tests (instrumentados, sem UI)
  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache de dependências Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Execute integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: default
          arch: x86_64
          profile: Nexus 6
          ram-size: 2048M
          heap-size: 512M
          disk-size: 2048M
          force-avd-creation: true
          emulator-options: -no-snapshot-save -no-snapshot-load -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: false
          script: |
            echo "Emulator is ready, running integration tests..."
            ./gradlew integrationTests

      - name: Upload integration-test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: |
            app/build/reports
            app/build/outputs/androidTest-results

  # 4) UI tests
  ui-tests:
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache de dependências Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Execute UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          target: default
          arch: x86_64
          profile: Nexus 6
          ram-size: 2048M
          heap-size: 512M
          disk-size: 2048M
          force-avd-creation: true
          emulator-options: -no-snapshot-save -no-snapshot-load -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim
          disable-animations: false
          script: |
            echo "Emulator is ready, running UI tests..."
            ./gradlew uiTests

      - name: Upload UI-test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-results
          path: |
            app/build/reports
            app/build/outputs/androidTest-results

  # 5) Consolidação final de artefatos
  upload-reports:
    needs: ui-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Publish all test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-test-results
          path: |
            app/build/reports
            app/build/outputs/androidTest-results
