name: Todo CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  # 1) Build do app
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache de dependências Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 30
          build-tools: "30.0.3"
          components: |
            platform-tools
            emulator
            system-images;android-30;google_apis;x86_64

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

  # 2) Unit tests
  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache de dependências Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Run unit tests
        run: ./gradlew unitTests

  # 3) Integration tests (instrumentados, sem UI)
  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache de dependências Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 30
          build-tools: "30.0.3"
          components: |
            platform-tools
            emulator
            system-images;android-30;google_apis;x86_64

      - name: Execute integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          ram-size: 2048M
          disk-size: 4096M
          heap-size: 512M
          cores: 2
          force-avd-creation: true
          disable-linux-hw-accel: true
          emulator-boot-timeout: 900
          emulator-options: -no-window -no-audio -no-snapshot-save -no-snapshot-load -camera-back none -camera-front none -gpu swiftshader_indirect
          script: |
            echo "Waiting for emulator to be ready..."
            adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\''\r'\'') ]]; do sleep 1; done; input keyevent 82'
            echo "Emulator is ready, running tests..."
            ./gradlew integrationTests

      - name: Upload integration-test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: |
            app/build/reports
            app/build/outputs/androidTest-results

  # 4) UI tests
  ui-tests:
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache de dependências Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 30
          build-tools: "30.0.3"
          components: |
            platform-tools
            emulator
            system-images;android-30;google_apis;x86_64

      - name: Execute UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          ram-size: 2048M
          disk-size: 4096M
          heap-size: 512M
          cores: 2
          force-avd-creation: true
          disable-linux-hw-accel: true
          emulator-boot-timeout: 900
          emulator-options: -no-window -no-audio -no-snapshot-save -no-snapshot-load -camera-back none -camera-front none -gpu swiftshader_indirect
          script: |
            echo "Waiting for emulator to be ready..."
            adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed | tr -d '\''\r'\'') ]]; do sleep 1; done; input keyevent 82'
            echo "Emulator is ready, running tests..."
            ./gradlew uiTests

      - name: Upload UI-test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ui-test-results
          path: |
            app/build/reports
            app/build/outputs/androidTest-results

  # 5) Consolidação final de artefatos
  upload-reports:
    needs: ui-tests
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Publish all test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-test-results
          path: |
            app/build/reports
            app/build/outputs/androidTest-results
