# .github/workflows/mobile-ci.yml
name: Todo CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  # 1) Build do app
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}
      - id: sdk
        uses: android-actions/setup-android@v2
        with:
          api-level: 35
          build-tools: "35.0.0"
          components: |
            platform-tools
            emulator
            system-images;android-35;google_apis;x86_64
      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

  # 2) Unit tests (sem device)
  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Run unit tests
        run: ./gradlew unitTests

  # 3) Integration tests (instrumentados no pacote test.integration)
  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # === Inicia o emulador para tests instrumentados ===
      - name: Create & Start Emulator
        run: |
          echo "no" | avdmanager create avd -n test -k "system-images;android-35;google_apis;x86_64" --force
          nohup emulator -avd test -no-window -no-audio &

      - name: Wait for device
        run: |
          adb wait-for-device
          adb shell settings put global window_animation_scale 0
          adb shell settings put global transition_animation_scale 0
          adb shell settings put global animator_duration_scale 0

      - name: Run integration tests
        run: ./gradlew integrationTests

      - name: Upload integration-test reports
        uses: actions/upload-artifact@v3
        with:
          name: integration-test-results
          path: |
            app/build/reports
            app/build/outputs/androidTest-results

  # 4) UI tests (instrumentados no pacote test.ui)
  ui-tests:
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Reusa o mesmo AVD já criado
      - name: Start Emulator (reuse)
        run: |
          nohup emulator -avd test -no-window -no-audio &

      - name: Wait for device
        run: |
          adb wait-for-device

      - name: Run UI tests
        run: ./gradlew uiTests

      - name: Upload UI-test reports
        uses: actions/upload-artifact@v3
        with:
          name: ui-test-results
          path: |
            app/build/reports
            app/build/outputs/androidTest-results

  # 5) Artifacts consolidados (opcional)
  upload-all:
    needs: [ui-tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: all-test-results
          path: |
            app/build/reports
            app/build/outputs/androidTest-results
