name: Todo CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  # 1) Build do app
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache de dependências Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: "35.0.0"
          components: |
            platform-tools
            emulator
            system-images;android-35;google_apis;x86_64

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug

  # 2) Unit tests
  unit-tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache de dependências Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Run unit tests
        run: ./gradlew unitTests

  # 3) Integration tests (instrumentados, sem UI)
  integration-tests:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache de dependências Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: "35.0.0"
          components: |
            platform-tools
            emulator
            system-images;android-35;google_apis;x86_64

      - name: Execute integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          disable-linux-hw-accel: true
          emulator-boot-timeout: 600
          emulator-options: -no-window -no-audio -no-snapshot
          script: |
            adb wait-for-device
            ./gradlew integrationTests

      - name: Upload integration-test reports
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: |
            app/build/reports
            app/build/outputs/androidTest-results

  # 4) UI tests
  ui-tests:
    needs: integration-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache de dependências Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','gradle-wrapper.properties') }}

      - name: Instalar Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-level: 35
          build-tools: "35.0.0"
          components: |
            platform-tools
            emulator
            system-images;android-35;google_apis;x86_64

      - name: Execute UI tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64
          force-avd-creation: true
          disable-linux-hw-accel: true
          emulator-boot-timeout: 600
          emulator-options: -no-window -no-audio -no-snapshot
          script: |
            adb wait-for-device
            ./gradlew uiTests

      - name: Upload UI-test reports
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: |
            app/build/reports
            app/build/outputs/androidTest-results

  # 5) Consolidação final de artefatos
  upload-reports:
    needs: ui-tests
    runs-on: ubuntu-latest
    steps:
      - name: Publish all test artifacts
        uses: actions/upload-artifact@v4
        with:
          name: all-test-results
          path: |
            app/build/reports
            app/build/outputs/androidTest-results
